/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/create-event': RouteRecordInfo<'/create-event', '/create-event', Record<never, never>, Record<never, never>>,
    '/events/[id]': RouteRecordInfo<'/events/[id]', '/events/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/events/search': RouteRecordInfo<'/events/search', '/events/search', Record<never, never>, Record<never, never>>,
    '/organizer/[id]': RouteRecordInfo<'/organizer/[id]', '/organizer/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/organizer/create-event/[id]': RouteRecordInfo<'/organizer/create-event/[id]', '/organizer/create-event/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/organizer/events/[id]': RouteRecordInfo<'/organizer/events/[id]', '/organizer/events/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
