name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shipping:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: github.event_name == 'push'

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: profileorg/wowtogo-fe-dev
        build-args: |
          API_URL=${{ secrets.BACKEND_URL }}
          FE_DOMAIN=${{ secrets.FRONTEND_URL }}
      if: github.event_name == 'push'

  deploy:
    needs: shipping
    runs-on: self-hosted

    steps:
    - name: SSH to VPS and deploy Docker container
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 165.22.243.107
        username: nhatsang
        password: 290503sang
        script: |
          docker pull profileorg/wowtogo-fe-dev:latest
          docker stop wowtogo-container || true
          docker rm wowtogo-container || true
          docker run -d --name wowtogo-container -p 80:80 profileorg/wowtogo-fe-dev:latest
